# Generated by Django 5.1.2 on 2024-10-14 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
        ("proveedor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id_producto",
                    models.IntegerField(
                        db_column="id_producto",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_column="nombre", max_length=20)),
                ("precio_unitario", models.FloatField(db_column="precio_unitario")),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categoria.categoria",
                    ),
                ),
                (
                    "id_proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedor.proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
            },
        ),
    ]
