# Generated by Django 5.1.2 on 2024-10-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="producto",
            table="Producto",
        ),
    ]
