# Generated by Django 5.1.2 on 2024-10-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id_proveedor",
                    models.IntegerField(
                        db_column="id_proveedor",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(db_column="nombre", max_length=20, unique=True),
                ),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["nombre"],
            },
        ),
    ]
